ARG BASE_CONTAINER=jupyter/minimal-notebook
FROM $BASE_CONTAINER

LABEL maintainer="Ryan Francis Eudy"

#USER root

# ffmpeg for matplotlib anim & dvipng+cm-super for latex labels
#RUN apt-get update && \
#    apt-get install -y --no-install-recommends ffmpeg dvipng cm-super && \
#    apt-get clean && rm -rf /var/lib/apt/lists/*

# Install Python Libraries
#RUN pip install --quiet --no-cache-dir \
#    'numpy' 

#USER $NB_UID

#WORKDIR $HOME
